name: Build Padavan for K2P

on:
  push:
    branches: [ "main" ]          # 只在 main 分支推送时触发构建
  workflow_dispatch:              # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: k2p-padavan

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libtool-bin gperf python3-docutils autopoint gettext ccache

      - name: Build firmware
        run: make K2P TOOLCHAIN=mipsel-linux-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: padavan-k2p
          path: trunk/images/*.trx

  publish:
    needs: build
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}  # 仅 main 分支发布
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: padavan-k2p
          path: firmware

      - name: Set release tag
        run: echo "TAG_NAME=K2P-$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Create Git tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.TAG_NAME }}
          force_push_tag: true

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.TAG_NAME }}
          artifacts: "firmware/*.trx"
          allowUpdates: true
          prerelease: false
