# .github/workflows/toolchain.yml
name: Build Cross Toolchain (for K2P)

on:
  workflow_dispatch:  # 仅手动触发，避免误跑

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget

      - name: Build mipsel-linux-musl toolchain
        run: |
          set -e
          make CT_TARGET=mipsel-linux-musl CT_VERSION=1.26.0
          cd toolchain/crosstool-ng-1.26.0/toolchain-mipsel
          tar cJf ../../../mipsel-linux-musl.tar.xz .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: toolchain-mipsel-linux-musl
          path: mipsel-linux-musl.tar.xz

      - name: Publish to GitHub Release
        uses: svenstaro/upload-release-action@2.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mipsel-linux-musl.tar.xz
          asset_name: mipsel-linux-musl.tar.xz
          tag: toolchain-v1.26.0
          release_name: Padavan Toolchain (mipsel-linux-musl)
          overwrite: false
